"""initial schema

Revision ID: f30fe2a4c440
Revises: 
Create Date: 2026-06-18 14:07:19.089958

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f30fe2a4c440'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('toss_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'WEB', name='device_platform'), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_device_token')
    )
    op.create_index(op.f('ix_device_tokens_store_id'), 'device_tokens', ['store_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_store_id'), 'materials', ['store_id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pos_menu_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_pos_menu_code'), 'menus', ['pos_menu_code'], unique=False)
    op.create_index(op.f('ix_menus_store_id'), 'menus', ['store_id'], unique=False)
    op.create_table('toss_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('WEBHOOK', 'POLLING', name='order_source'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'order_id', name='uq_toss_order_store_order')
    )
    op.create_index(op.f('ix_toss_orders_order_id'), 'toss_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_toss_orders_store_id'), 'toss_orders', ['store_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_changed', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reason_code', sa.Enum('SALE', 'WASTE', 'AUDIT', 'CANCEL', name='reason_code'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_material_id'), 'inventory_transactions', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reference'), 'inventory_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_store_id'), 'inventory_transactions', ['store_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id', 'material_id', name='uq_recipe_menu_material')
    )
    op.create_index(op.f('ix_recipes_material_id'), 'recipes', ['material_id'], unique=False)
    op.create_index(op.f('ix_recipes_menu_id'), 'recipes', ['menu_id'], unique=False)
    op.create_index(op.f('ix_recipes_store_id'), 'recipes', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_store_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_menu_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_material_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_inventory_transactions_store_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_reference'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_material_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_toss_orders_store_id'), table_name='toss_orders')
    op.drop_index(op.f('ix_toss_orders_order_id'), table_name='toss_orders')
    op.drop_table('toss_orders')
    op.drop_index(op.f('ix_menus_store_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_pos_menu_code'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_materials_store_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_store_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Postgres ENUM 타입은 테이블 삭제로 자동 제거되지 않으므로 명시적으로 정리한다.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="reason_code").drop(bind, checkfirst=True)
        sa.Enum(name="order_source").drop(bind, checkfirst=True)
        sa.Enum(name="device_platform").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
